---
title: "AlunosUFCG"
author: "Rodolfo Viana"
date: "13-06-2015"
output: html_document
---

Sys.setlocale(locale = "C")

```{r}
# cut -d',' -f2,3 submissao.csv > t


library(dplyr)

training <- read.csv("~/Projetos/DataAnalysis/Assignment5/training_sem_acento.csv")

training <- filter(training, PERIODO_RELATIVO == 1)

#Transformação para factor
training$COD_CURSO <- as.factor(training$COD_CURSO)
training$COD_EVASAO <- as.factor(training$COD_EVASAO)
training$CURSO <- as.factor(training$CURSO)
training$DEPARTAMENTO <- as.factor(training$DEPARTAMENTO)
training$DISCIPLINA <- as.factor(training$DISCIPLINA)

#Missing
levels(training$SITUACAO)[1] = NA
levels(training$PERIODO_INGRESSO)[1] = NA
levels(training$CURSO)[1] = NA
levels(training$CREDITOS)[1] = NA
levels(training$DEPARTAMENTO)[1] = NA
levels(training$DISCIPLINA)[1] = NA

#Primeiro periodo
set.seed(12345) 
primeiro_periodo <- filter(training, PERIODO_RELATIVO == 1)

primeiro_training <- primeiro_periodo[order(runif(nrow(primeiro_periodo))), ]

#Divisao de treino e teste
training_train <- primeiro_training[1:round(0.9*nrow(primeiro_periodo)), ]
training_test <- primeiro_training[round(0.9*nrow(primeiro_periodo)):nrow(primeiro_periodo), ]
prop.table(table(training_train$COD_EVASAO))
prop.table(table(training_test$COD_EVASAO))

library("C50")

model <- C5.0(training_train[,c(5,7,9,11)], training_train$COD_EVASAO)
model
summary(model)
```

Testando o modelo

```{r}
training_test$CURSO <- NULL
training_test$DEPARTAMENTO <- NULL
training_test$DISCIPLINA <- NULL

pred <- predict(model, training_test[,c(5,7,9,11)])

true_eva <- training_test$COD_EVASAO == 1
table(pred, true_eva)
```


```{r}
test_first_round_kaggle <- read.csv("~/Projetos/DataAnalysis/Assignment5/test_first_round_kaggle_sem_acento.csv")

test_first_round_kaggle$CREDITOS <- as.factor(test_first_round_kaggle$CREDITO)
test_first_round_kaggle$CURSO <- as.factor(test_first_round_kaggle$CURSO)
test_first_round_kaggle$DEPARTAMENTO <- as.factor(test_first_round_kaggle$DEPARTAMENTO)
test_first_round_kaggle$DISCIPLINA <- as.factor(test_first_round_kaggle$DISCIPLINA)
test_first_round_kaggle$COD_CURSO <- as.factor(test_first_round_kaggle$COD_CURSO)
test_first_round_kaggle$MEDIA <- as.numeric(as.character(test_first_round_kaggle$MEDIA))
test_first_round_kaggle$PERIODO_RELATIVO <- as.numeric(test_first_round_kaggle$PERIODO_RELATIVO)

test_first_round_kaggle$PERIODO_INGRESSO <- as.factor(test_first_round_kaggle$PERIODO_INGRESSO)

pred <- predict(model, test_first_round_kaggle[,c(5,7,9, 11)])
summary(pred)

submissao <- cbind(test_first_round_kaggle["COD_EVASAO"], COD_EVASAO=pred)

test_matriculas <- select(test_first_round_kaggle, MATRICULA)
submissao <- cbind(df_test["MATRICULA"], COD_EVASAO=prediction)

save(select(test_first_round_kaggle, MATRICULA, COD_EVASAO),file="submissao.csv")
write.csv(select(test_first_round_kaggle, ID, COD_EVASAO),file="submissao.csv")

str(test_first_round_kaggle)
```

